/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    val input = if (args.size == 1) {
        when(args[0]) {
            "test" -> readInput("../../inputTest.txt")
            "run" -> readInput("../../input1.txt")
            else -> {
                println("Invalid argument '${args[0]}' will use the test config. (Valid arguments: 'test', 'run')")
                readInput("../../inputTest.txt")
            }
        }
    } else {
        readInput("../../input1.txt")
    }
}

fun readInput(inputFile: String): String {
    val file = File(inputFile)
    return file.readText()
}